meta_product_name: "UpLift"
meta_title: "UpLift - Change lives one favour at a time"
meta_description: "Exchange favours. Make an impact locally."
meta_image: "upliftlogo.png" # should exist in `app/assets/images/`
